---
# tasks file for insert_cert

- name: Copy All Remote Hosts Certificates To Remote Hosts
  copy:
    src: /etc/ansible/remote_crt/{{ ansible_hostname }}/{{ ansible_hostname }}.crt
    dest: /etc/pki/tls/certs/{{ ansible_hostname }}.crt

- name: Ensure SSLCertificateFile
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateFile'
    line: SSLCertificateFile "{{ remote_cert_path }}"

- name: Ensure SSLCertificateKeyFile
  lineinfile:
    path: /etc/httpd/conf.d/ssl.conf
    regexp: '^SSLCertificateKeyFile'
    line: SSLCertificateKeyFile "{{ remote_private_key_path }}"
  notify:
    - Restart firewalld

- name: Copy CA CERT To All Remote Hosts
  copy:
    src: /etc/ansible/CA_CERT/ca_master.crt
    dest: /etc/pki/ca-trust/source/anchors/ca_master.crt

- name: Add CA Certificate To Local ca-trust Store
  shell: update-ca-trust
  notify:
    - Restart firewalld

- name: Create Pem File Of Cert + Private Key
  shell: cat "{{ remote_private_key_path }}" "{{ remote_cert_path }}" > "{{ remote_pem_file_path }}"

- name: Restart keepalived
  service:
    name: keepalived
    state: restarted
